### ISSUE TITLE
Make relationship options work

### ISSUE THREAD

**Issue by ociu** [ociu/sphinx-traceability-extension#1]
Stereotypes are supported in syntax and stored, but not used for the moment. They should be used as the README states, to classify relationships and allow filtering.

**Comment by DrLulz** [comment]
Would be great for this. Thank you regardless.

**Comment by ociu** [comment]
New syntax added in README file, easier and more flexible. This Issue remains, but changed title to keep in sync with README. What were stereotypes are now relationship types, and are written directly as directive options (no UML-like syntax).

**Comment by fkromer** [comment]
What is the status of this issue? I wrote the draft of a test for the integration of the package with sphinx.ext.autodoc. I was able to get some html output but i got some errors while building with python code with docstrings which included relationsships which i defined in conf.py with option traceability_relationships. You can find all related files of the test here: https://github.com/fkromer/sphinx-traceability-extension/tree/master/tests/docs/autodoc

**Comment by ociu** [comment]
Done, at last!! Big change but kept it simple.
Did not try to build your example, but the syntax is correct. Should work now. Let me know in case error remains.

**Comment by fkromer** [comment]
Thanks a lot for adding the support. I did update my test and it works pretty fine. The only thing i discovered is that if there is missing a referenced item (in my case: SW_REQ_003 which is referenced by SW_TEST_003) one is not notified about this when creating a traceability matrix. Is my matrix syntax correct? (For the moment i placed the test items into test_code.py cause the test_code.py is not imported for some reason i did not catch right now.)
https://github.com/fkromer/sphinx-traceability-extension/tree/master/tests/docs/autodoc/docs
