### ISSUE TITLE
List/table titles not working

### ISSUE THREAD

**Issue by ociu** [ociu/sphinx-traceability-extension#10]
Though specified for v0.1.0, the title argument passed to directives `item-list` and `item-matrix` has no effect in the output. To correct:
- `item-list`: remove argument. Title has no sense, as a title can be put before and there is no need to reference the list.
- `item-matrix`: title should be inserted as in a `table` directive, also as a reference.

**Comment by SteinHeselmans** [comment]
Display title of item-matrix added in https://github.com/melexis/sphinx-traceability-extension/pull/35 (amongst other improvements). Should be easy to backport.

**Comment by SteinHeselmans** [comment]
Using admonition for the title of all directives in https://github.com/melexis/sphinx-traceability-extension/pull/37 . Can be ported to this fork.
