### ISSUE TITLE
If no traceability directives are used, the sphinx build fails

### ISSUE THREAD

**Issue by marklakata** [ociu/sphinx-traceability-extension#15]
If you add the `traceability` module to the list of sphinx extensions, but you don't actually use any of the new directives, the sphinx build fails.

    Exception occurred:
      File "/home/UNIXHOME/mlakata/p4/acq/Sequel/top/doc/sphinxcontrib/traceability.py", line 237, in     process_item_nodes
        all_items = sorted(env.traceability_all_items, key=naturalsortkey)
    AttributeError: BuildEnvironment instance has no attribute 'traceability_all_items'

A simple fix is

    def process_item_nodes(app, doctree, fromdocname):
    ...
        env = app.builder.env

        if not hasattr(env, 'traceability_all_items'):
            return

**Comment by ociu** [comment]
Yes, I've reproduced the error. It will happen also if you use query directives (`item-list`, `item-matrix`) but not the `item` directive. I'll make a general correction to solve both situations.

Thank you!
