### ISSUE TITLE
Console traceability debug output 

### ISSUE THREAD

**Issue by fkromer** [ociu/sphinx-traceability-extension#16]
It seems like when item directives (here: SW_REQ_001) reference other item directives (here: SW_TEST_001) which do not exist the user is just able to get informed about this by observing the document output (html, pdf, ...) of the `.. item-matrix::` directive. Some debug or warning console output during the build process would be helpful to get around this manual traceability checking.

```
.. item:: SW_REQ_001 Some requirement.
    :validated_by: SW_TEST_001
```

... like in /sphinx-traceability-extension/tests/docs/autodoc/docs/_build/index.html what you can build with #17
This issue will be addressed by #18.

**Comment by SteinHeselmans** [comment]
warning messages about missing items are added to the Melexis fork of this project (https://github.com/melexis/sphinx-traceability-extension)
