### ISSUE TITLE
Incompatibility with .. only (and .. ifconfig)

### ISSUE THREAD

**Issue by SteinHeselmans** [ociu/sphinx-traceability-extension#20]
When an item is conditionally included in the document using the **..only** directive (or the ..ifconfig) directive, and the condition on the tags is not met
- the content of the item does not show up in the document : ok
- the item does still show up in the item-list, and item-matrix automatically generated lists/tables

syntax used:

```
.. only :: RANDOM_TAG_WHICH_IS_NOT_DEFINED_IN_CONF_DOT_PY

    .. item:: my_item It is an item with a caption
        :depends_on: another_item

        This item does not show up in the document, but does show up in the generated lists and tables
```

Doc for ..only and how to specify tags on command line or conf.py, can be found here http://www.sphinx-doc.org/en/stable/markup/misc.html

**Comment by bavovanachte** [comment]
In fact, this seems more of a sphinx issue than an issue of this plugin. 

This might be worth a read: https://github.com/pfalcon/sphinx_selective_exclude

**Comment by SteinHeselmans** [comment]
That is a nice plugin, and it seems to work in combination with traceability as well :+1: Too bad it is not available in a pip-package...
