### ISSUE TITLE
How to add extension?

### ISSUE THREAD

**Issue by dheater** [ociu/sphinx-traceability-extension#26]
Basic question.

I've done the pip install. Now how do import the extension? I tried adding to `extensions` in `conf.py`, but when I run `make html` I get:
```
Extension error:
Could not import extension traceability (exception: No module named 'traceability')
make: *** [Makefile:20: html] Error 2
```
and
```
Extension error:
Could not import extension sphinxcontrib-traceability (exception: No module named 'sphinxcontrib-traceability')
make: *** [Makefile:20: html] Error 2
```

**Comment by dheater** [comment]
`sphinxcontrib.traceability` might be the correct name? It at least doesn't complain about no module, but it gives a different error:

```
Extension error:
Could not import extension sphinxcontrib.traceability (exception: cannot import name 'NoUri' from 'sphinx.environment' (/home/dheater/.platformio/penv/lib/python3.8/site-packages/sphinx/environment/__init__.py))
make: *** [Makefile:20: html] Error 2
```

**Comment by ociu** [comment]
`sphinxcontrib.traceability` is the correct name.

Which version of Sphinx are you using? It seems that `NoUri` has been removed fom `sphinx.environment` in v4.0.
I'll fix it. In the meantime if you downgrade Sphinx it will work.

**Comment by dheater** [comment]
I was using `sphinx 3.5.2`,  I've tried downgrading to 3.4.3 and 3.3.1 but still getting the same error.

**Comment by dheater** [comment]
But, yes. Commenting out `from sphinx.environment import NoUri` in `traceability.py` seems to work!

**Comment by ociu** [comment]
NoUri error existed since v2.0 (March 2019), huge downgrade :)... Now it works with both old and new versions.

Thank you!
