### ISSUE TITLE
Directives in docstrings possible?

### ISSUE THREAD

**Issue by fkromer** [ociu/sphinx-traceability-extension#6]
Is it possible to place the directives of the extension into docstrings? This would allow to use [sphinx.ext.autodoc](http://www.sphinx-doc.org/en/stable/ext/autodoc.html?highlight=autodoc) and other extensions which include docstrings into the documentation automatically.

**Comment by ociu** [comment]
Yes, they work in docstrings, exactly as they do in any document.
When you put a traceability item in a docstring in code that is processed by Sphinx, that traceability item can trace to and be traced by any other item in the same Sphinx project.

**Comment by fkromer** [comment]
Nice, thanks a lot!
